name: BanPlugin
version: '1.0-SNAPSHOT'
main: me.shadow.banplugin.BanPlugin
api-version: '1.20'
commands:
  ban:
    description: Simple ban plugin
    usage: /<command>
  unban:
    description: Simple unban plugin
    usage: /<command>